const location = [
  { value: "Afghanistan", label: 'Afghanistan' },
  { value: "Albania", label: 'Albania' },
  { value: "Algeria", label: 'Algeria' },
  { value: "Andorra", label: 'Andorra' },
  { value: "Angola", label: 'Angola' },
  { value: "Antigua and Barbuda", label: 'Antigua and Barbuda' },
  { value: "Argentina", label: 'Argentina' },
  { value: "Armenia", label: 'Armenia' },
  { value: "Australia", label: 'Australia' },
  { value: "Austria", label: 'Austria' },
  { value: "Azerbaijan", label: 'Azerbaijan' },
  { value: "Bahamas", label: 'Bahamas' },
  { value: "Bahrain", label: 'Bahrain' },
  { value: "Bangladesh", label: 'Bangladesh' },
  { value: "Barbados", label: 'Barbados' },
  { value: "Belarus", label: 'Belarus' },
  { value: "Belgium", label: 'Belgium' },
  { value: "Belize", label: 'Belize' },
  { value: "Benin", label: 'Benin' },
  { value: "Bhutan", label: 'Bhutan' },
  { value: "Bolivia", label: 'Bolivia' },
  { value: "Bosnia", label: 'Bosnia' },
  { value: "Botswana", label: 'Botswana' },
  { value: "Brazil", label: 'Brazil' },
  { value: "Brunei", label: 'Brunei' },
  { value: "Bulgaria", label: 'Bulgaria' },
  { value: "Burkina Faso", label: 'Burkina Faso' },
  { value: "Burundi", label: 'Burundi' },
  { value: "Côte", label: 'Côte' },
  { value: "Cabo Verde", label: 'Cabo Verde' },
  { value: "Cambodia", label: 'Cambodia' },
  { value: "Cameroon", label: 'Cameroon' },
  { value: "Canada", label: 'Canada' },
  { value: "Central", label: 'Central' },
  { value: "Chad", label: 'Chad' },
  { value: "Chile", label: 'Chile' },
  { value: "China", label: 'China' },
  { value: "Colombia", label: 'Colombia' },
  { value: "Comoros", label: 'Comoros' },
  { value: "Congo", label: 'Congo' },
  { value: "Costa Rica", label: 'Costa Rica' },
  { value: "Croatia", label: 'Croatia' },
  { value: "Cuba", label: 'Cuba' },
  { value: "Cyprus", label: 'Cyprus' },
  { value: "Czechia", label: 'Czechia' },
  { value: "Democratic", label: 'Democratic' },
  { value: "Denmark", label: 'Denmark' },
  { value: "Djibouti", label: 'Djibouti' },
  { value: "Dominica", label: 'Dominica' },
  { value: "Dominican", label: 'Dominican' },
  { value: "Ecuador", label: 'Ecuador' },
  { value: "Egypt", label: 'Egypt' },
  { value: "El Salvador", label: 'El Salvador' },
  { value: "Equatorial", label: 'Equatorial' },
  { value: "Eritrea", label: 'Eritrea' },
  { value: "Estonia", label: 'Estonia' },
  { value: "Eswatini", label: 'Eswatini' },
  { value: "Ethiopia", label: 'Ethiopia' },
  { value: "Fiji", label: 'Fiji' },
  { value: "Finland", label: 'Finland' },
  { value: "France", label: 'France' },
  { value: "Gabon", label: 'Gabon' },
  { value: "Gambia", label: 'Gambia' },
  { value: "Georgia", label: 'Georgia' },
  { value: "Germany", label: 'Germany' },
  { value: "Ghana", label: 'Ghana' },
  { value: "Greece", label: 'Greece' },
  { value: "Grenada", label: 'Grenada' },
  { value: "Guatemala", label: 'Guatemala' },
  { value: "Guinea", label: 'Guinea' },
  { value: "Guinea-Bissau", label: 'Guinea-Bissau' },
  { value: "Guyana", label: 'Guyana' },
  { value: "Haiti", label: 'Haiti' },
  { value: "Holy See", label: 'Holy See' },
  { value: "Honduras", label: 'Honduras' },
  { value: "Hungary", label: 'Hungary' },
  { value: "Iceland", label: 'Iceland' },
  { value: "India", label: 'India' },
  { value: "Indonesia", label: 'Indonesia' },
  { value: "Iran", label: 'Iran' },
  { value: "Iraq", label: 'Iraq' },
  { value: "Ireland", label: 'Ireland' },
  { value: "Israel", label: 'Israel' },
  { value: "Italy", label: 'Italy' },
  { value: "Jamaica", label: 'Jamaica' },
  { value: "Japan", label: 'Japan' },
  { value: "Jordan", label: 'Jordan' },
  { value: "Kazakhstan", label: 'Kazakhstan' },
  { value: "Kenya", label: 'Kenya' },
  { value: "Kiribati", label: 'Kiribati' },
  { value: "Kuwait", label: 'Kuwait' },
  { value: "Kyrgyzstan", label: 'Kyrgyzstan' },
  { value: "Laos", label: 'Laos' },
  { value: "Latvia", label: 'Latvia' },
  { value: "Lebanon", label: 'Lebanon' },
  { value: "Lesotho", label: 'Lesotho' },
  { value: "Liberia", label: 'Liberia' },
  { value: "Libya", label: 'Libya' },
  { value: "Liechtenstein", label: 'Liechtenstein' },
  { value: "Lithuania", label: 'Lithuania' },
  { value: "Luxembourg", label: 'Luxembourg' },
  { value: "Madagascar", label: 'Madagascar' },
  { value: "Malawi", label: 'Malawi' },
  { value: "Malaysia", label: 'Malaysia' },
  { value: "Maldives", label: 'Maldives' },
  { value: "Mali", label: 'Mali' },
  { value: "Malta", label: 'Malta' },
  { value: "Marshall Islands", label: 'Marshall Islands' },
  { value: "Mauritania", label: 'Mauritania' },
  { value: "Mauritius", label: 'Mauritius' },
  { value: "Mexico", label: 'Mexico' },
  { value: "Micronesia", label: 'Micronesia' },
  { value: "Moldova", label: 'Moldova' },
  { value: "Monaco", label: 'Monaco' },
  { value: "Mongolia", label: 'Mongolia' },
  { value: "Montenegro", label: 'Montenegro' },
  { value: "Morocco", label: 'Morocco' },
  { value: "Mozambique", label: 'Mozambique' },
  { value: "Myanmar", label: 'Myanmar' },
  { value: "Namibia", label: 'Namibia' },
  { value: "Nauru", label: 'Nauru' },
  { value: "Nepal", label: 'Nepal' },
  { value: "Netherlands", label: 'Netherlands' },
  { value: "New Zealand", label: 'New Zealand' },
  { value: "Nicaragua", label: 'Nicaragua' },
  { value: "Niger", label: 'Niger' },
  { value: "Nigeria", label: 'Nigeria' },
  { value: "North Korea", label: 'North Korea' },
  { value: "North Macedonia", label: 'North Macedonia' },
  { value: "Norway", label: 'Norway' },
  { value: "Oman", label: 'Oman' },
  { value: "Pakistan", label: 'Pakistan' },
  { value: "Palau", label: 'Palau' }
]

export default location;